In [1]:
# generate random integer values
import random
from random import seed
from random import randint

suit=['hearts', 'diamonds', 'spades', 'clubs']
card=['Ace of','2 of','3 of','4 of','5 of','6 of','7 of','8 of','9 of','10 of','Jack of','Queen of','King of']

# seed random number generator if want same answer every time
#random.choices(iterable,k=number) : draws number things from the list, with duplicates
#random.sample(iterable,k=number) : draws number things from the list, no duplicates

# generate some integers
for _ in range(52):
	suits = random.choice(suit)
 
for _ in range(52): #chose 52 times since 52 cards
  cards=random.choice(card)

print(cards,suits)

10 of hearts


In [2]:
#whole deck
#change suits so same length as cards in deck

s=[suit]*13
c=[card]*4

#flatten lists 
suit_list = sum(s, [])
card_list = sum(c, [])
#print(cards,suits)

random.sample(list(zip(card_list, suit_list)), 10) #how do I clean this up (w/o commas and stuff)


[('2 of', 'diamonds'),
 ('8 of', 'hearts'),
 ('6 of', 'clubs'),
 ('7 of', 'clubs'),
 ('King of', 'diamonds'),
 ('Jack of', 'spades'),
 ('3 of', 'hearts'),
 ('5 of', 'diamonds'),
 ('Ace of', 'spades'),
 ('10 of', 'spades')]

Cards without repetition

In [3]:
#use random sample to not repeat 
# generate some integers
for _ in range(52):
	suitx = random.sample(suit,1)
 
for _ in range(52): #chose 52 times since 52 cards
  cardx=random.sample(card,1)

print(cardx,suitx)

['Ace of'] ['clubs']


choosing from deck, matrix style

In [4]:
import random
import numpy as np

#declaring suits
diamonds=[1,2,3,4,5,6,7,8,9,10,11,12,13]
hearts=[1,2,3,4,5,6,7,8,9,10,11,12,13]
spades=[1,2,3,4,5,6,7,8,9,10,11,12,13]
clubs=[1,2,3,4,5,6,7,8,9,10,11,12,13]

deck=np.empty([4,13])

deckrandom=[[],[],[],[]] #going to show order the cards where randomly drawn for each suit

suits=[1,2,3,4]
#diamonds=1, hearts=2, clubs=3, spades=4
while len(suits) > 0 :
    suit=random.choice(suits) #randomly choose a suit
    if suit==1:
        card=random.choice(diamonds) #draw a card
        diamonds.remove(card)#remove that card from diamonds array, shortens array
        deckrandom[0].append(card) #diamonds is first index, adding card drawn to first diamonds (0 position) in array
#If there are no diamonds left then remove diamonds from the suits set
        if len(diamonds)==0:
            suits.remove(suit) #remove diamond from suits array
    elif suit==2:
        card=random.choice(hearts)
        hearts.remove(card)
        deckrandom[1].append(card)
#If there are no hearts left then remove diamonds from the suits set
        if len(hearts)==0:
            suits.remove(suit)
    elif suit==3:
        card=random.choice(clubs)
        clubs.remove(card)
        deckrandom[2].append(card)
        if len(clubs)==0:
            suits.remove(suit)
    elif suit==4:
        card=random.choice(spades)
        spades.remove(card)
        deckrandom[3].append(card)
        if len(spades)==0:
            suits.remove(suit) #remove spades
    deck[suit-1][card-1]=card  #if I used suit=[0,1,2,3] then dont need -1, index starts at 0 not 1, so for suits=4, there is no 4 index in suits array only up to position 3
    #print('suit='+str(suit)+ ';card='+str(card))
print('check for full array so all of deck was drawn', deck) #check to make sure matrix full, in order
print('order numbers were drawn from each suit',deckrandom) #shows order we drew in for each suit

check for full array so all of deck was drawn [[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13.]
 [ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13.]
 [ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13.]
 [ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13.]]
order numbers were drawn from each suit [[1, 3, 6, 11, 5, 8, 9, 4, 12, 2, 10, 7, 13], [8, 4, 7, 1, 2, 5, 11, 3, 13, 12, 9, 6, 10], [12, 2, 11, 5, 9, 3, 8, 1, 7, 13, 6, 10, 4], [11, 13, 10, 6, 8, 12, 7, 4, 3, 5, 1, 9, 2]]
